/**
 * Recommendation Component
 * Displays AI-generated vendor recommendation
 */

import React from 'react';
import './Recommendation.css';

const Recommendation = ({ recommendation }) => {
  if (!recommendation) {
    return null;
  }

  // Handle error cases
  if (recommendation.error || recommendation.message) {
    return (
      <div className="recommendation-container">
        <h2>🤖 AI Recommendation</h2>
        <div className="info-message">
          {recommendation.error || recommendation.message}
        </div>
      </div>
    );
  }

  return (
    <div className="recommendation-container">
      <h2>🤖 AI Recommendation</h2>
      
      <div className="recommendation-card">
        <div className="recommended-vendor">
          <div className="trophy-icon">🏆</div>
          <div className="vendor-info">
            <div className="label">Recommended Vendor</div>
            <div className="vendor-name">{recommendation.recommendedVendor}</div>
          </div>
        </div>

        <div className="reason-section">
          <h3>📝 Why this vendor?</h3>
          <p className="reason-text">{recommendation.reason}</p>
        </div>

        {recommendation.keyFactors && recommendation.keyFactors.length > 0 && (
          <div className="factors-section">
            <h3>🔑 Key Decision Factors</h3>
            <ul className="factors-list">
              {recommendation.keyFactors.map((factor, index) => (
                <li key={index}>
                  <span className="factor-icon">✓</span>
                  {factor}
                </li>
              ))}
            </ul>
          </div>
        )}

        {recommendation.savingsInfo && (
          <div className="savings-section">
            <div className="savings-icon">💡</div>
            <div className="savings-text">{recommendation.savingsInfo}</div>
          </div>
        )}
      </div>

      <div className="disclaimer">
        <strong>Note:</strong> This recommendation is generated by AI based on the extracted data. 
        Please verify all information before making final procurement decisions.
      </div>
    </div>
  );
};

export default Recommendation;
